{{- if and .Values.config (eq .Values.configExistingSecretName "") }}
apiVersion: v1
kind: {{ if .Values.secretConfig -}} Secret {{- else -}} ConfigMap {{- end }}
metadata:
  name: {{ template "prometheus-domain-exporter.fullname" . }}
  namespace: {{ template "prometheus-domain-exporter.namespace" . }}
  labels:
    {{- include "prometheus-domain-exporter.labels" . | nindent 4 }}
{{ if .Values.secretConfig -}} stringData: {{- else -}} data: {{- end }}
  blackbox.yaml: |
{{ toYaml .Values.config | indent 4 }}
{{- end }}
